---
# https://molecule.readthedocs.io/ci/#github-actions

name: "Integración Contínua"

on: [push]

jobs:
  construir:
    runs-on: ubuntu-22.04
    steps:
      - name: "Registrar el código fuente"
        uses: actions/checkout@v2

      - name: "Configurar Python 3"
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: "Instalar las dependencias para las pruebas"
        run: pip3 install ansible-core molecule
